"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
} from "react";

type Language = "es" | "en" | "pt";

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, namespace?: string) => any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

// Event emitter for language changes (ensures all components re-render)
type LanguageChangeListener = (language: Language) => void;
let listeners: Set<LanguageChangeListener> = new Set();

const notifyLanguageChange = (language: Language) => {
  listeners.forEach((listener) => listener(language));
};

export const subscribeToLanguageChange = (listener: LanguageChangeListener) => {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
};

// Comprehensive translations
const translationsEs = {
  common: {
    __locale__: "es-AR",
    language: "Idioma",
    spanish: "Español",
    english: "English",
    portuguese: "Português",
    darkMode: "Modo Oscuro",
    lightMode: "Modo Claro",
    settings: "Configuración",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    close: "Cerrar",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    warning: "Advertencia",
    info: "Información",
    login: "Ingresar",
    logout: "Cerrar Sesión",
    register: "Registrarse",
    email: "Correo Electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    required: "Requerido",
    optional: "Opcional",
    features: "Características",
    pricing: "Precios",
    documentation: "Documentación",
    support: "Soporte",
    help: "Centro de Ayuda",
    contact: "Contacto",
    serviceStatus: "Estado del Servicio",
    backToTop: "Volver al Inicio",
    legal: "Legal",
    terms: "Términos de Servicio",
    privacy: "Privacidad",
    allRightsReserved: "Todos los derechos reservados",
  },
  landing: {
    hero: {
      badge: "⭐ Sistema 100% en la nube - Sin instalaciones",
      titleMain: "Tu Punto de Venta",
      titleHighlight: "en la Nube",
      description:
        "Sistema de facturación completo para kioscos, almacenes y minimercados. Rápido, fácil y sin complicaciones.",
      startFree: "Empezar Gratis →",
      viewFeatures: "Ver Características",
    },
    stats: {
      cloud: "En la Nube",
      initialPlan: "Plan Inicial",
      available: "Disponible",
    },
    features: [
      {
        title: "Súper Rápido",
        description:
          "Interfaz optimizada como supermercado. Vende en segundos con código de barras.",
      },
      {
        title: "100% en la Nube",
        description:
          "Sin instalaciones. Accede desde cualquier navegador, en cualquier dispositivo.",
      },
      {
        title: "Control de Stock",
        description:
          "Gestiona inventario automáticamente con cada venta. Alertas de stock bajo.",
      },
      {
        title: "Reportes en Vivo",
        description:
          "Ventas, caja, productos más vendidos. Todo actualizado en tiempo real.",
      },
      {
        title: "Multi-Usuario",
        description:
          "Gestiona cajeros y administradores. Control de permisos y descuentos.",
      },
      {
        title: "Seguro y Confiable",
        description:
          "Tus datos protegidos con Supabase. Backup automático en la nube.",
      },
    ],
    howItWorks: {
      badge: "Cómo funciona",
      title: "Configura, vende y crece",
      subtitle: "Todo listo en minutos, sin instalaciones ni hardware extra.",
      steps: [
        {
          title: "Configura tu negocio",
          description:
            "Carga productos, precios y usuarios en minutos desde cualquier dispositivo.",
        },
        {
          title: "Vende más rápido",
          description:
            "Código de barras, atajos y tickets listos para cobrar sin fricciones.",
        },
        {
          title: "Controla tu operación",
          description:
            "Reportes en vivo, stock y caja en un solo lugar, siempre actualizado.",
        },
      ],
    },
    cta: {
      title: "¿Listo para modernizar tu negocio?",
      subtitle:
        "Únete a cientos de negocios que ya usan VentaPlus para vender más rápido",
      startFreeNow: "Empezar Gratis Ahora →",
      noCard: "Sin tarjeta de crédito • Configuración en 2 minutos",
    },
  },
  dashboard: {
    welcome: "Bienvenido",
    currentPlan: "Tu plan actual",
    planBasic: "Plan Básico",
    planProfessional: "Plan Profesional",
    planEnterprise: "Plan Empresarial",
    upgradeToPro: "Actualizar a Pro",
    status: "Estado",
    nextRenewal: "Próxima Renovación",
    posSale: "Venta POS",
    cashRegister: "Caja rápida",
    products: "Productos",
    inventory: "Gestionar inventario",
    reports: "Reportes",
    analytics: "Ver análisis",
    admin: "Admin",
    systemSettings: "Configuración del sistema",
    quickStats: "Estadísticas Rápidas",
    salesToday: "Ventas Hoy",
    totalRevenue: "Ingresos Totales",
  },
  errors: {
    generic: "Algo salió mal. Por favor intente de nuevo",
    unauthorized: "No autorizado",
    invalidOrExpiredToken: "Token inválido o expirado",
    missingAuthHeader: "Falta encabezado de autorización",
    forbidden: "Acceso denegado",
    notFound: "No encontrado",
    serverError: "Error del servidor",
    networkError: "Error de conexión",
    validationError: "Error de validación",
    productCodeRequired: "El código del producto es requerido",
    productNameRequired: "El nombre del producto es requerido",
    productPriceRequired: "El precio del producto es requerido",
    invalidPrice: "El precio debe ser un número válido",
    productCreated: "Producto creado correctamente",
    productUpdated: "Producto actualizado correctamente",
    productDeleted: "Producto eliminado correctamente",
    errorCreatingProduct: "Error al crear el producto",
    errorUpdatingProduct: "Error al actualizar el producto",
    errorDeletingProduct: "Error al eliminar el producto",
    errorFetchingProducts: "Error al obtener los productos",
    invalidEmail: "Correo electrónico inválido",
    passwordTooShort: "La contraseña debe tener al menos 6 caracteres",
    passwordsDoNotMatch: "Las contraseñas no coinciden",
    userAlreadyExists: "El usuario ya existe",
    invalidCredentials: "Credenciales inválidas",
    sessionExpired: "Tu sesión ha expirado. Por favor inicia sesión nuevamente",
    errorSaving: "Error al guardar",
    errorLoading: "Error al cargar",
    errorDeleting: "Error al eliminar",
    noOpenCashRegister: "No hay caja abierta",
    invalidAction: "Acción inválida",
    invalidAmount: "Monto inválido",
    internalServerError: "Error interno del servidor",
    missingRequiredFields: "Faltan campos requeridos",
    errorLoadingConfig: "Error al cargar configuración",
    clientNameRequired: "Debes ingresar el nombre del cliente",
    cuitRequired: "CUIT es requerido para facturas ARCA",
    ivaTypeRequired: "Selecciona el tipo de IVA para facturas ARCA",
    companyNameRequired: "Nombre de la empresa es requerido",
    cuitRucDniRequired: "CUIT/RUC/DNI es requerido",
    billingEmailRequired: "Email de facturación es requerido",
    errorSavingSupplier: "Error al guardar proveedor",
    supplierDeletedSuccess: "Proveedor eliminado exitosamente",
    errorDeletingSupplier: "Error al eliminar proveedor",
    selectValidCSV: "Por favor selecciona un archivo CSV válido",
    emptyCSVFile: "El archivo CSV está vacío o no tiene datos",
    csvMustContainName: 'El CSV debe contener al menos la columna "nombre"',
    noValidSuppliersFound:
      "No se encontraron proveedores válidos en el archivo",
    errorProcessingCSV: "Error al procesar el archivo CSV",
    suppliersImportedSuccess: (count: number) =>
      `${count} proveedores importados exitosamente`,
    errorLoadingSales: "Error al cargar las ventas",
    errorRegisteringPurchase: "Error al registrar la compra",
    purchaseRegisteredSuccess: "¡Compra registrada exitosamente!",
    paymentError: "Error en el pago",
    errorCompletingSale: "Error al completar la venta",
    errorProcessingSale: "Error al procesar la venta. Intenta nuevamente",
    noDataToExport: "No hay datos para exportar",
    confirmDeleteExpense: "¿Estás seguro de eliminar este gasto?",
    productCodeExists: "El código del producto ya existe",
    emailInUse: "El correo electrónico ya está en uso",
    cannotDeleteSelf: "No puedes eliminarte a ti mismo",
    invalidPlanId: "Plan inválido",
    noFileReceived: "No se recibió ningún archivo",
    invalidFile: "Archivo inválido",
    errorImportingProducts: "Error al importar productos",
  },
  messages: {
    welcome: "Bienvenido",
    goodbye: "Hasta luego",
    confirmDelete: "¿Estás seguro de que deseas eliminar esto?",
    confirmAction: "¿Estás seguro?",
    processing: "Procesando...",
    loading: "Cargando...",
    noResults: "Sin resultados",
    noData: "Sin datos disponibles",
  },
  auth: {
    login: {
      title: "Ingresar",
      email: "Correo Electrónico",
      password: "Contraseña",
      submit: "Ingresar",
      forgotPassword: "¿Olvidaste tu contraseña?",
      noAccount: "¿No tienes cuenta?",
      registerLink: "Registrarse",
    },
    forgotPassword: {
      title: "Recuperar Contraseña",
      subtitle:
        "Ingresa tu email y te enviaremos un enlace para restablecer tu contraseña",
      email: "Correo Electrónico",
      submit: "Enviar Enlace de Recuperación",
      backToLogin: "Volver al inicio de sesión",
      emailSent: "Email enviado",
      emailSentMessage:
        "Si existe una cuenta con ese email, recibirás un enlace de recuperación",
    },
    resetPassword: {
      title: "Restablecer Contraseña",
      subtitle: "Ingresa tu nueva contraseña",
      password: "Nueva Contraseña",
      confirmPassword: "Confirmar Nueva Contraseña",
      submit: "Restablecer Contraseña",
      success: "Contraseña restablecida exitosamente",
      invalidToken: "El enlace de recuperación es inválido o ha expirado",
    },
    register: {
      title: "Registrarse",
      fullName: "Nombre Completo",
      email: "Correo Electrónico",
      password: "Contraseña",
      confirmPassword: "Confirmar Contraseña",
      submit: "Crear Cuenta",
      haveAccount: "¿Ya tienes una cuenta?",
      loginLink: "Ingresar",
    },
  },
  pricing: {
    title: "Planes simples y transparentes",
    subtitle: "Empieza gratis y crece cuando lo necesites",
    free: "Plan Gratuito",
    freePrice: "$0",
    freeSubtitle: "para siempre",
    freeDescription: "Ideal para empezar",
    pro: "Plan Pro",
    proPrice: "$24.990",
    proSubtitle: "ARS/mes",
    proDescription: "Sin límites para crecer",
    mostPopular: "Más Popular",
    freeFeatures: [
      "Hasta 100 productos",
      "Hasta 2 usuarios",
      "Punto de venta completo",
      "Control de caja",
      "Reportes básicos",
      "Stock básico",
    ],
    proFeatures: [
      "Productos ilimitados",
      "Usuarios ilimitados",
      "Todo lo del plan gratuito",
      "Gestión de clientes",
      "Ventas a crédito (fiado)",
      "Gestión de gastos",
      "Reportes avanzados",
      "Soporte prioritario",
    ],
    startFree: "Empezar Gratis",
    tryFree: "Probar 14 días gratis",
  },
  subscriptionProModal: {
    titlePrefix: "Suscripción -",
    billingInfo: "Información de facturación",
    fields: {
      businessNameLabel: "Nombre de la Empresa",
      businessNamePlaceholder: "Nombre de tu empresa",
      cuitRucDniLabel: "CUIT/RUC/DNI",
      cuitRucDniPlaceholder: "20-12345678-9",
      billingEmailLabel: "Email de Facturación",
      billingEmailPlaceholder: "facturacion@tuempresa.com",
      phoneLabel: "Teléfono",
      phonePlaceholder: "011 1234-5678",
    },
    buttons: {
      continuePayment: "Continuar al Pago",
      processing: "Procesando...",
    },
  },
  navigation: {
    home: "Inicio",
    dashboard: "Panel de Control",
    products: "Productos",
    sales: "Ventas",
    customers: "Clientes",
    reports: "Reportes",
    settings: "Configuración",
    profile: "Perfil",
  },
  profile: {
    title: "Perfil",
    account: "Cuenta",
    loading: "Cargando perfil",
    personalInfo: "Información personal",
    userData: "Datos del usuario",
    updateDescription:
      "Actualiza tu nombre y correo. La contraseña es opcional.",
    goToDashboard: "Ir al panel",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    phone: "Teléfono",
    phonePlaceholder: "Ej: +54 9 11 1234 5678",
    role: "Rol",
    businessName: "Nombre del negocio",
    businessPlaceholder: "Tu comercio",
    password: "Contraseña (opcional)",
    passwordPlaceholder: "Dejar en blanco para mantener",
    reset: "Restablecer",
    save: "Guardar cambios",
    updateSuccess: "Perfil actualizado correctamente",
    updateError: "No se pudo guardar. Intenta nuevamente.",
    updateErrorGeneric: "No se pudo actualizar el perfil",
    back: "Volver",
  },
  pos: {
    nav: {
      posSale: "Punto de Venta",
      cashRegister: "Control de Caja",
      products: "Productos",
      categories: "Categorías",
      stock: "Stock",
      clients: "Clientes",
      suppliers: "Proveedores",
      expenses: "Gastos",
      reports: "Reportes",
      fiscalReports: "Reportes Fiscales",
      users: "Usuarios",
      keyboardConfig: "Configuración de Teclas",
      businessConfig: "Configuración de Negocio",
      planComparison: "Comparación de Planes",
    },
    labels: {
      add: "Agregar",
      edit: "Editar",
      delete: "Eliminar",
      save: "Guardar",
      cancel: "Cancelar",
      search: "Buscar",
      filter: "Filtrar",
      sort: "Ordenar",
      import: "Importar",
      export: "Exportar",
      print: "Imprimir",
      actions: "Acciones",
      name: "Nombre",
      description: "Descripción",
      price: "Precio",
      code: "Código",
      quantity: "Cantidad",
      total: "Total",
      subtotal: "Subtotal",
      tax: "Impuesto",
      discount: "Descuento",
      payment: "Pago",
      customer: "Cliente",
      date: "Fecha",
      time: "Hora",
      status: "Estado",
      active: "Activo",
      inactive: "Inactivo",
      pending: "Pendiente",
      completed: "Completado",
      cancelled: "Cancelado",
    },
    messages: {
      confirmDelete: "¿Estás seguro de que deseas eliminar esto?",
      noData: "No hay datos disponibles",
      loading: "Cargando...",
      errorLoading: "Error al cargar datos",
      clientFetchError: "Error al cargar clientes",
      selectClient: "Seleccionar cliente...",
      noClients: "No hay clientes",
      clientsUpgradeRequired:
        "Búsqueda de clientes disponible solo en el plan Pro",
      errorCreating: "Error al crear elemento",
      errorUpdating: "Error al actualizar elemento",
      errorDeleting: "Error al eliminar elemento",
      successCreate: "Elemento creado exitosamente",
      successUpdate: "Elemento actualizado exitosamente",
      successDelete: "Elemento eliminado exitosamente",
      required: "Este campo es requerido",
      selectOne: "Por favor selecciona un elemento",
    },
    pages: {
      pos: {
        title: "Punto de Venta",
        noProducts: "No hay productos para vender",
        selectProduct: "Selecciona un producto",
        quantity: "Cantidad",
        addToCart: "Agregar al Carrito",
        cart: "Carrito",
        total: "Total",
        clearCart: "Limpiar Carrito",
        checkout: "Pagar",
        cash: "Efectivo",
        card: "Tarjeta",
        transfer: "Transferencia",
      },
      products: {
        title: "Productos",
        addProduct: "Agregar Producto",
        editProduct: "Editar Producto",
        deleteProduct: "Eliminar Producto",
        productCode: "Código del Producto",
        productName: "Nombre del Producto",
        description: "Descripción",
        price: "Precio",
        cost: "Costo",
        quantity: "Cantidad",
        category: "Categoría",
        supplier: "Proveedor",
        barcode: "Código de Barras",
      },
      categories: {
        title: "Categorías",
        addCategory: "Agregar Categoría",
        editCategory: "Editar Categoría",
        deleteCategory: "Eliminar Categoría",
        categoryName: "Nombre de Categoría",
        description: "Descripción",
      },
      stock: {
        title: "Stock",
        inventory: "Inventario",
        quantity: "Cantidad",
        alertLevel: "Nivel de Alerta",
        lastUpdate: "Última Actualización",
        adjustStock: "Ajustar Stock",
        stockHistory: "Historial de Stock",
      },
      clients: {
        title: "Clientes",
        addClient: "Agregar Cliente",
        editClient: "Editar Cliente",
        deleteClient: "Eliminar Cliente",
        name: "Nombre",
        email: "Email",
        phone: "Teléfono",
        address: "Dirección",
        city: "Ciudad",
        state: "Provincia",
        zipCode: "Código Postal",
        creditLimit: "Límite de Crédito",
        creditUsed: "Crédito Usado",
      },
      suppliers: {
        title: "Proveedores",
        addSupplier: "Agregar Proveedor",
        editSupplier: "Editar Proveedor",
        deleteSupplier: "Eliminar Proveedor",
        name: "Nombre",
        email: "Email",
        phone: "Teléfono",
        address: "Dirección",
        city: "Ciudad",
        state: "Provincia",
        contact: "Contacto",
      },
      expenses: {
        title: "Gastos",
        addExpense: "Agregar Gasto",
        editExpense: "Editar Gasto",
        deleteExpense: "Eliminar Gasto",
        description: "Descripción",
        amount: "Monto",
        category: "Categoría",
        date: "Fecha",
        paymentMethod: "Método de Pago",
      },
      reports: {
        title: "Reportes",
        salesReport: "Reporte de Ventas",
        stockReport: "Reporte de Stock",
        expensesReport: "Reporte de Gastos",
        clientsReport: "Reporte de Clientes",
        profitReport: "Reporte de Ganancias",
        dateRange: "Rango de Fechas",
        exportPDF: "Exportar a PDF",
        exportExcel: "Exportar a Excel",
        totalSales: "Total de Ventas",
        totalExpenses: "Total de Gastos",
        totalProfit: "Total de Ganancias",
      },
      cashRegister: {
        title: "Control de Caja",
        openCash: "Abrir Caja",
        closeCash: "Cerrar Caja",
        balance: "Balance",
        initialAmount: "Monto Inicial",
        finalAmount: "Monto Final",
        expected: "Esperado",
        actual: "Actual",
        difference: "Diferencia",
        cashRegisterId: "ID de Caja",
        openedBy: "Abierto por",
        closedBy: "Cerrado por",
        openTime: "Hora de Apertura",
        closeTime: "Hora de Cierre",
        status: "Estado",
        open: "Abierto",
        closed: "Cerrado",
        movements: {
          opening: "Apertura de caja",
          withdrawal: "Retiro de caja",
          creditNote: "Nota de crédito",
          noReason: "Sin motivo especificado",
        },
      },
    },
    ui: {
      loading: "Cargando POS...",
      title: "POS - {role}",
      closedTitle: "Caja Cerrada",
      closedDescription:
        'Debes abrir una caja desde la sección "Control de Caja" para comenzar a vender',
      scanPlaceholder: "Escanear o ingresar código de barras... (F6)",
      searchPlaceholder: "Buscar producto por nombre o código... (F5)",
      searching: "Buscando...",
      tipsTitle: "Tips rápidos:",
      tipsBodyStart: "Usa el lector de barras o busca por nombre. Navega con",
      tipsBodyEnd: "y presiona",
      tipsBodyAdd: "para agregar.",
      startTyping: "Empezá a escribir para buscar",
      noProductsFound: "No se encontraron productos",
      codeLabel: "Código:",
      stockLabel: "Stock:",
      addButton: "Agregar",
      cartTitle: "Carrito",
      clearCart: "Limpiar Carrito",
      cartEmpty: "Carrito vacío",
      cartEmptySubtitle: "Escanea o busca productos para comenzar",
      remove: "Eliminar",
      quantity: "Cant.",
      discount: "Descuento",
      total: "Total",
      subtotal: "Subtotal",
      totalDiscount: "Descuento",
      tax21: "IVA 21%",
      discountLimitExceeded: "El descuento supera tu límite",
      discountInvalid: "Descuento inválido",
      discountNegative: "El descuento debe ser 0 o mayor",
      discountExceedsSubtotal:
        "El descuento no puede superar el subtotal de la línea",
      discountExceedsUserLimit: "El descuento supera tu límite",
      weightQuantityHint:
        "Use punto para decimales y coma para miles (ej.: 1.560 o 1,560)",
      paymentMethod: "Método de Pago",
      paymentOptions: {
        cash: "Efectivo",
        card: "Tarjeta",
        check: "Cheque",
        online: "Online",
        bankTransfer: "Transferencia Bancaria",
        qr: "Código QR",
        account: "Cuenta corriente",
      },
      accountLabel: "Cuenta",
      balanceLabel: "Saldo",
      balanceDueLabel: "Saldo pendiente",
      balanceCreditLabel: "Saldo a favor",
      viewAccount: "Ver cuenta",
      accountTitle: "Cuenta del cliente",
      registerPayment: "Registrar pago",
      paymentAmount: "Monto",
      paymentNote: "Detalle",
      savePayment: "Guardar pago",
      accountMovements: "Movimientos",
      noAccountMovements: "Sin movimientos",
      accountCharge: "Cargo",
      accountPayment: "Pago",
      accountAdjustment: "Ajuste",
      accountLoadError: "Error al cargar cuenta",
      accountPaymentSaved: "Pago registrado",
      accountPaymentError: "Error al registrar pago",
      accountRequiresClient: "Selecciona un cliente para cobrar a cuenta",
      accountInvalidAmount: "Monto inválido",
      accountOverpayError: "El pago supera el saldo pendiente",
      processing: "Procesando...",
      checkout: "Finalizar Venta",
      checkoutSuccess: "¡Venta completada exitosamente!",
      checkoutError: "Error al completar la venta",
      checkoutProcessError: "Error al procesar la venta. Intenta nuevamente.",
      insufficientStock:
        "Stock insuficiente para {name}. Disponible: {available}, solicitado: {requested}",
      print: "Imprimir",
      close: "Cerrar",
      roles: {
        admin: "Administrador",
        supervisor: "Supervisor",
        cashier: "Cajero",
        user: "Usuario",
      },
      // Keyboard POS translations
      keyboardPOS: "POS con Teclado",
      quantityFirst: "Ingrese cantidad primero, luego código del producto",
      productCodeBarcode: "Código de Producto / Código de Barras",
      scanOrEnterCode: "Escanear o ingresar código...",
      pressEnterToAdd: "Presione Enter para agregar • Esc para cancelar",
      keyboardShortcuts: "Atajos de Teclado",
      confirmAdd: "Confirmar / Agregar",
      cancel: "Cancelar / Limpiar",
      multiplier: "Multiplicador (50*código)",
      changeCustomer: "Cambiar cliente",
      findCustomer: "Buscar cliente",
      newCustomer: "Nuevo cliente",
      removeCustomer: "Quitar cliente",
      examples: "Ejemplos",
      example1:
        "Escriba '5' → Enter → Escanee/Ingrese código → Enter = 5 unidades",
      example2: "Escriba '0.325' → Enter → Escanear = 0.325 kg",
      example3:
        "Escriba '50*697202601252361' → Enter = 50 unidades instantáneamente",
      quantityHint: "Ingrese cantidad o use multiplicador: 50*código",
      enterProductCode: "Por favor ingrese un código de producto",
      invalidQuantity: "Cantidad inválida",
      productNotFound: "Producto no encontrado",
      outOfStock: "Producto sin stock",
      addedToCart: "agregado al carrito",
      errorAddingProduct: "Error al agregar producto",
      changeCustomerType: "Cambiar tipo de cliente",
      searchCustomer: "Buscar cliente",
      advancedSearch: "Búsqueda Avanzada",
      clickToExpand: "Haga clic para expandir",
    },
  },
};

const translationsEn = {
  common: {
    __locale__: "en-US",
    language: "Language",
    spanish: "Español",
    english: "English",
    portuguese: "Português",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    settings: "Settings",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    login: "Login",
    logout: "Logout",
    register: "Sign Up",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    required: "Required",
    optional: "Optional",
    features: "Features",
    pricing: "Pricing",
    documentation: "Documentation",
    support: "Support",
    help: "Help Center",
    contact: "Contact",
    serviceStatus: "Service Status",
    backToTop: "Back to Top",
    legal: "Legal",
    terms: "Terms of Service",
    privacy: "Privacy",
    allRightsReserved: "All rights reserved",
  },
  landing: {
    hero: {
      badge: "⭐ 100% Cloud System - No installations",
      titleMain: "Your Point of Sale",
      titleHighlight: "in the Cloud",
      description:
        "Complete billing system for kiosks, stores and mini-markets. Fast, easy and hassle-free.",
      startFree: "Start Free →",
      viewFeatures: "View Features",
    },
    stats: {
      cloud: "In the Cloud",
      initialPlan: "Initial Plan",
      available: "Available",
    },
    features: [
      {
        title: "Super Fast",
        description:
          "Optimized interface like supermarkets. Sell in seconds with barcodes.",
      },
      {
        title: "100% in the Cloud",
        description: "No installations. Access from any browser on any device.",
      },
      {
        title: "Stock Control",
        description:
          "Manage inventory automatically with each sale. Low stock alerts.",
      },
      {
        title: "Live Reports",
        description:
          "Sales, cash register, top products. All updated in real time.",
      },
      {
        title: "Multi-User",
        description:
          "Manage cashiers and admins. Control permissions and discounts.",
      },
      {
        title: "Secure and Reliable",
        description:
          "Your data protected with Supabase. Automatic cloud backups.",
      },
    ],
    howItWorks: {
      badge: "How it works",
      title: "Set up, sell, and grow",
      subtitle: "Ready in minutes with no installs or extra hardware.",
      steps: [
        {
          title: "Set up your business",
          description:
            "Add products, pricing, and users in minutes from any device.",
        },
        {
          title: "Sell faster",
          description:
            "Barcode scanning, shortcuts, and receipts built for speed.",
        },
        {
          title: "Stay in control",
          description:
            "Live reports, stock, and cash in one always‑updated place.",
        },
      ],
    },
    cta: {
      title: "Ready to modernize your business?",
      subtitle:
        "Join hundreds of businesses already using VentaPlus to sell faster",
      startFreeNow: "Start Free Now →",
      noCard: "No credit card • Setup in 2 minutes",
    },
  },
  dashboard: {
    welcome: "Welcome",
    currentPlan: "Your current plan",
    planBasic: "Basic Plan",
    planProfessional: "Professional Plan",
    planEnterprise: "Enterprise Plan",
    upgradeToPro: "Upgrade to Pro",
    status: "Status",
    nextRenewal: "Next Renewal",
    posSale: "POS Sale",
    cashRegister: "Quick cash register",
    products: "Products",
    inventory: "Manage inventory",
    reports: "Reports",
    analytics: "View analytics",
    admin: "Admin",
    systemSettings: "System settings",
    quickStats: "Quick Stats",
    salesToday: "Sales Today",
    totalRevenue: "Total Revenue",
  },
  errors: {
    generic: "Something went wrong. Please try again",
    unauthorized: "Unauthorized",
    invalidOrExpiredToken: "Invalid or expired token",
    missingAuthHeader: "Missing authorization header",
    forbidden: "Access denied",
    notFound: "Not found",
    serverError: "Server error",
    networkError: "Network error",
    validationError: "Validation error",
    productCodeRequired: "Product code is required",
    productNameRequired: "Product name is required",
    productPriceRequired: "Product price is required",
    invalidPrice: "Price must be a valid number",
    productCreated: "Product created successfully",
    productUpdated: "Product updated successfully",
    productDeleted: "Product deleted successfully",
    errorCreatingProduct: "Error creating product",
    errorUpdatingProduct: "Error updating product",
    errorDeletingProduct: "Error deleting product",
    errorFetchingProducts: "Error fetching products",
    invalidEmail: "Invalid email",
    passwordTooShort: "Password must be at least 6 characters",
    passwordsDoNotMatch: "Passwords do not match",
    userAlreadyExists: "User already exists",
    invalidCredentials: "Invalid credentials",
    sessionExpired: "Your session has expired. Please sign in again",
    errorSaving: "Error saving",
    errorLoading: "Error loading",
    errorDeleting: "Error deleting",
    noOpenCashRegister: "No open cash register",
    invalidAction: "Invalid action",
    invalidAmount: "Invalid amount",
    internalServerError: "Internal server error",
    missingRequiredFields: "Missing required fields",
    errorLoadingConfig: "Error loading configuration",
    clientNameRequired: "You must enter the customer name",
    cuitRequired: "CUIT is required for ARCA invoices",
    ivaTypeRequired: "Select the VAT type for ARCA invoices",
    companyNameRequired: "Company name is required",
    cuitRucDniRequired: "CUIT/RUC/ID is required",
    billingEmailRequired: "Billing email is required",
    errorSavingSupplier: "Error saving supplier",
    supplierDeletedSuccess: "Supplier deleted successfully",
    errorDeletingSupplier: "Error deleting supplier",
    selectValidCSV: "Please select a valid CSV file",
    emptyCSVFile: "The CSV file is empty or has no data",
    csvMustContainName: 'CSV must contain at least the "nombre" column',
    noValidSuppliersFound: "No valid suppliers found in the file",
    errorProcessingCSV: "Error processing CSV file",
    suppliersImportedSuccess: (count: number) =>
      `${count} suppliers imported successfully`,
    errorLoadingSales: "Error loading sales",
    errorRegisteringPurchase: "Error registering purchase",
    purchaseRegisteredSuccess: "Purchase registered successfully!",
    paymentError: "Payment error",
    errorCompletingSale: "Error completing sale",
    errorProcessingSale: "Error processing sale. Please try again",
    noDataToExport: "No data to export",
    confirmDeleteExpense: "Are you sure you want to delete this expense?",
    productCodeExists: "Product code already exists",
    emailInUse: "Email is already in use",
    cannotDeleteSelf: "You cannot delete yourself",
    invalidPlanId: "Invalid plan",
    noFileReceived: "No file received",
    invalidFile: "Invalid file",
    errorImportingProducts: "Error importing products",
  },
  messages: {
    welcome: "Welcome",
    goodbye: "Goodbye",
    confirmDelete: "Are you sure you want to delete this?",
    confirmAction: "Are you sure?",
    processing: "Processing...",
    loading: "Loading...",
    noResults: "No results",
    noData: "No data available",
  },
  auth: {
    login: {
      title: "Login",
      email: "Email",
      password: "Password",
      submit: "Login",
      forgotPassword: "Forgot your password?",
      noAccount: "Don't have an account?",
      registerLink: "Sign Up",
    },
    forgotPassword: {
      title: "Recover Password",
      subtitle:
        "Enter your email and we'll send you a link to reset your password",
      email: "Email",
      submit: "Send Recovery Link",
      backToLogin: "Back to login",
      emailSent: "Email sent",
      emailSentMessage:
        "If an account exists with that email, you will receive a recovery link",
    },
    resetPassword: {
      title: "Reset Password",
      subtitle: "Enter your new password",
      password: "New Password",
      confirmPassword: "Confirm New Password",
      submit: "Reset Password",
      success: "Password reset successfully",
      invalidToken: "The recovery link is invalid or has expired",
    },
    register: {
      title: "Sign Up",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      submit: "Create Account",
      haveAccount: "Already have an account?",
      loginLink: "Login",
    },
  },
  pricing: {
    title: "Simple and transparent plans",
    subtitle: "Start free and grow when you need to",
    free: "Free Plan",
    freePrice: "$0",
    freeSubtitle: "forever",
    freeDescription: "Perfect to get started",
    pro: "Pro Plan",
    proPrice: "$24.990",
    proSubtitle: "ARS/month",
    proDescription: "Unlimited to grow",
    mostPopular: "Most Popular",
    freeFeatures: [
      "Up to 100 products",
      "Up to 2 users",
      "Complete point of sale",
      "Cash register control",
      "Basic reports",
      "Basic stock",
    ],
    proFeatures: [
      "Unlimited products",
      "Unlimited users",
      "Everything from free plan",
      "Customer management",
      "Credit sales",
      "Expense management",
      "Advanced reports",
      "Priority support",
    ],
    startFree: "Start Free",
    tryFree: "Try 14 days free",
  },
  subscriptionProModal: {
    titlePrefix: "Subscription -",
    billingInfo: "Billing information",
    fields: {
      businessNameLabel: "Company Name",
      businessNamePlaceholder: "Your company name",
      cuitRucDniLabel: "Tax ID",
      cuitRucDniPlaceholder: "20-12345678-9",
      billingEmailLabel: "Billing Email",
      billingEmailPlaceholder: "billing@yourcompany.com",
      phoneLabel: "Phone",
      phonePlaceholder: "+1 (555) 123-4567",
    },
    buttons: {
      continuePayment: "Continue to Payment",
      processing: "Processing...",
    },
  },
  navigation: {
    home: "Home",
    dashboard: "Dashboard",
    products: "Products",
    sales: "Sales",
    customers: "Customers",
    reports: "Reports",
    settings: "Settings",
    profile: "Profile",
  },
  profile: {
    title: "Profile",
    account: "Account",
    loading: "Loading profile",
    personalInfo: "Personal information",
    userData: "User data",
    updateDescription: "Update your name and email. Password is optional.",
    goToDashboard: "Go to dashboard",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    phonePlaceholder: "E.g: +1 555 123 4567",
    role: "Role",
    businessName: "Business name",
    businessPlaceholder: "Your business",
    password: "Password (optional)",
    passwordPlaceholder: "Leave blank to keep current",
    reset: "Reset",
    save: "Save changes",
    updateSuccess: "Profile updated successfully",
    updateError: "Could not save. Please try again.",
    updateErrorGeneric: "Could not update profile",
    back: "Back",
  },
  pos: {
    nav: {
      posSale: "Point of Sale",
      cashRegister: "Cash Register",
      products: "Products",
      categories: "Categories",
      stock: "Stock",
      clients: "Customers",
      suppliers: "Suppliers",
      expenses: "Expenses",
      reports: "Reports",
      fiscalReports: "Fiscal Reports",
      users: "Users",
      keyboardConfig: "Keyboard Settings",
      businessConfig: "Business Settings",
      planComparison: "Plan Comparison",
    },
    labels: {
      add: "Add",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      import: "Import",
      export: "Export",
      print: "Print",
      actions: "Actions",
      name: "Name",
      description: "Description",
      price: "Price",
      code: "Code",
      quantity: "Quantity",
      total: "Total",
      subtotal: "Subtotal",
      tax: "Tax",
      discount: "Discount",
      payment: "Payment",
      customer: "Customer",
      date: "Date",
      time: "Time",
      status: "Status",
      active: "Active",
      inactive: "Inactive",
      pending: "Pending",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    messages: {
      confirmDelete: "Are you sure you want to delete this?",
      noData: "No data available",
      loading: "Loading...",
      errorLoading: "Error loading data",
      clientFetchError: "Error loading clients",
      selectClient: "Select client...",
      noClients: "No clients",
      clientsUpgradeRequired:
        "Customer search is available only on the Pro plan",
      errorCreating: "Error creating item",
      errorUpdating: "Error updating item",
      errorDeleting: "Error deleting item",
      successCreate: "Item created successfully",
      successUpdate: "Item updated successfully",
      successDelete: "Item deleted successfully",
      required: "This field is required",
      selectOne: "Please select an item",
    },
    pages: {
      pos: {
        title: "Point of Sale",
        noProducts: "No products to sell",
        selectProduct: "Select a product",
        quantity: "Quantity",
        addToCart: "Add to Cart",
        cart: "Cart",
        total: "Total",
        clearCart: "Clear Cart",
        checkout: "Checkout",
        cash: "Cash",
        card: "Card",
        transfer: "Transfer",
      },
      products: {
        title: "Products",
        addProduct: "Add Product",
        editProduct: "Edit Product",
        deleteProduct: "Delete Product",
        productCode: "Product Code",
        productName: "Product Name",
        description: "Description",
        price: "Price",
        cost: "Cost",
        quantity: "Quantity",
        category: "Category",
        supplier: "Supplier",
        barcode: "Barcode",
      },
      categories: {
        title: "Categories",
        addCategory: "Add Category",
        editCategory: "Edit Category",
        deleteCategory: "Delete Category",
        categoryName: "Category Name",
        description: "Description",
      },
      stock: {
        title: "Stock",
        inventory: "Inventory",
        quantity: "Quantity",
        alertLevel: "Alert Level",
        lastUpdate: "Last Update",
        adjustStock: "Adjust Stock",
        stockHistory: "Stock History",
      },
      clients: {
        title: "Customers",
        addClient: "Add Customer",
        editClient: "Edit Customer",
        deleteClient: "Delete Customer",
        name: "Name",
        email: "Email",
        phone: "Phone",
        address: "Address",
        city: "City",
        state: "State",
        zipCode: "Zip Code",
        creditLimit: "Credit Limit",
        creditUsed: "Credit Used",
      },
      suppliers: {
        title: "Suppliers",
        addSupplier: "Add Supplier",
        editSupplier: "Edit Supplier",
        deleteSupplier: "Delete Supplier",
        name: "Name",
        email: "Email",
        phone: "Phone",
        address: "Address",
        city: "City",
        state: "State",
        contact: "Contact",
      },
      expenses: {
        title: "Expenses",
        addExpense: "Add Expense",
        editExpense: "Edit Expense",
        deleteExpense: "Delete Expense",
        description: "Description",
        amount: "Amount",
        category: "Category",
        date: "Date",
        paymentMethod: "Payment Method",
      },
      reports: {
        title: "Reports",
        salesReport: "Sales Report",
        stockReport: "Stock Report",
        expensesReport: "Expenses Report",
        clientsReport: "Customers Report",
        profitReport: "Profit Report",
        dateRange: "Date Range",
        exportPDF: "Export to PDF",
        exportExcel: "Export to Excel",
        totalSales: "Total Sales",
        totalExpenses: "Total Expenses",
        totalProfit: "Total Profit",
      },
      cashRegister: {
        title: "Cash Register",
        openCash: "Open Cash Register",
        closeCash: "Close Cash Register",
        balance: "Balance",
        initialAmount: "Initial Amount",
        finalAmount: "Final Amount",
        expected: "Expected",
        actual: "Actual",
        difference: "Difference",
        cashRegisterId: "Register ID",
        openedBy: "Opened By",
        closedBy: "Closed By",
        openTime: "Open Time",
        closeTime: "Close Time",
        status: "Status",
        open: "Open",
        closed: "Closed",
        movements: {
          opening: "Opening cash",
          withdrawal: "Cash withdrawal",
          creditNote: "Credit note",
          noReason: "No reason specified",
        },
      },
    },
    ui: {
      loading: "Loading POS...",
      title: "POS - {role}",
      closedTitle: "Cash Register Closed",
      closedDescription:
        'You need to open a register from the "Cash Register" section to start selling',
      scanPlaceholder: "Scan or enter barcode... (F6)",
      searchPlaceholder: "Search product by name or code... (F5)",
      searching: "Searching...",
      tipsTitle: "Quick tips:",
      tipsBodyStart: "Use the barcode scanner or search by name. Navigate with",
      tipsBodyEnd: "and press",
      tipsBodyAdd: "to add.",
      startTyping: "Start typing to search",
      noProductsFound: "No products found",
      codeLabel: "Code:",
      stockLabel: "Stock:",
      addButton: "Add",
      cartTitle: "Cart",
      clearCart: "Clear Cart",
      cartEmpty: "Cart is empty",
      cartEmptySubtitle: "Scan or search products to start",
      remove: "Remove",
      quantity: "Qty.",
      discount: "Discount",
      total: "Total",
      subtotal: "Subtotal",
      totalDiscount: "Discount",
      tax21: "VAT 21%",
      discountLimitExceeded: "Discount exceeds your limit",
      discountInvalid: "Invalid discount",
      discountNegative: "Discount must be 0 or higher",
      discountExceedsSubtotal: "Discount cannot exceed line subtotal",
      discountExceedsUserLimit: "Discount exceeds your limit",
      weightQuantityHint:
        "Use period for decimals and comma for thousands (e.g., 1.560 or 1,560)",
      paymentMethod: "Payment Method",
      paymentOptions: {
        cash: "Cash",
        card: "Card",
        check: "Check",
        online: "Online",
        bankTransfer: "Bank Transfer",
        qr: "QR Code",
        account: "Account",
      },
      accountLabel: "Account",
      balanceLabel: "Balance",
      balanceDueLabel: "Amount due",
      balanceCreditLabel: "Credit balance",
      viewAccount: "View account",
      accountTitle: "Customer account",
      registerPayment: "Register payment",
      paymentAmount: "Amount",
      paymentNote: "Details",
      savePayment: "Save payment",
      accountMovements: "Movements",
      noAccountMovements: "No movements",
      accountCharge: "Charge",
      accountPayment: "Payment",
      accountAdjustment: "Adjustment",
      accountLoadError: "Failed to load account",
      accountPaymentSaved: "Payment recorded",
      accountPaymentError: "Failed to record payment",
      accountRequiresClient: "Select a customer to charge on account",
      accountInvalidAmount: "Invalid amount",
      accountOverpayError: "Payment exceeds amount due",
      processing: "Processing...",
      checkout: "Complete Sale",
      checkoutSuccess: "Sale completed successfully!",
      checkoutError: "Error completing the sale",
      checkoutProcessError: "Error processing the sale. Please try again.",
      insufficientStock:
        "Insufficient stock for {name}. Available: {available}, requested: {requested}",
      roles: {
        admin: "Administrator",
        supervisor: "Supervisor",
        cashier: "Cashier",
        user: "User",
      },
      // Keyboard POS translations
      keyboardPOS: "Keyboard POS",
      quantityFirst: "Enter quantity first, then product code",
      productCodeBarcode: "Product Code / Barcode",
      scanOrEnterCode: "Scan or enter code...",
      pressEnterToAdd: "Press Enter to add • Esc to cancel",
      keyboardShortcuts: "Keyboard Shortcuts",
      confirmAdd: "Confirm / Add",
      cancel: "Cancel / Clear",
      multiplier: "Multiplier (50*code)",
      changeCustomer: "Change customer",
      findCustomer: "Find customer",
      newCustomer: "New customer",
      removeCustomer: "Remove customer",
      examples: "Examples",
      example1: "Type '5' → Enter → Scan/Enter code → Enter = 5 units",
      example2: "Type '0.325' → Enter → Scan = 0.325 kg",
      example3: "Type '50*697202601252361' → Enter = 50 units instantly",
      quantityHint: "Enter quantity or use multiplier: 50*code",
      enterProductCode: "Please enter a product code",
      invalidQuantity: "Invalid quantity",
      productNotFound: "Product not found",
      outOfStock: "Product out of stock",
      addedToCart: "added to cart",
      errorAddingProduct: "Error adding product",
      changeCustomerType: "Change customer type",
      searchCustomer: "Search customer",
      advancedSearch: "Advanced Search",
      clickToExpand: "Click to expand",
    },
  },
};

const translationsPt = {
  common: {
    __locale__: "pt-BR",
    language: "Idioma",
    spanish: "Español",
    english: "English",
    portuguese: "Português",
    darkMode: "Modo Escuro",
    lightMode: "Modo Claro",
    settings: "Configurações",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    edit: "Editar",
    close: "Fechar",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    warning: "Aviso",
    info: "Informação",
    login: "Entrar",
    logout: "Sair",
    register: "Registrar",
    email: "Email",
    password: "Senha",
    confirmPassword: "Confirmar Senha",
    required: "Obrigatório",
    optional: "Opcional",
    features: "Recursos",
    pricing: "Preços",
    documentation: "Documentação",
    support: "Suporte",
    help: "Central de Ajuda",
    contact: "Contato",
    serviceStatus: "Status do Serviço",
    backToTop: "Voltar ao Topo",
    legal: "Legal",
    terms: "Termos de Serviço",
    privacy: "Privacidade",
    allRightsReserved: "Todos os direitos reservados",
  },
  landing: {
    hero: {
      badge: "⭐ Sistema 100% na nuvem - Sem instalações",
      titleMain: "Seu Ponto de Venda",
      titleHighlight: "na Nuvem",
      description:
        "Sistema de faturamento completo para quiosques, lojas e minimercados. Rápido, fácil e sem complicações.",
      startFree: "Começar Gratuitamente →",
      viewFeatures: "Ver Recursos",
    },
    stats: {
      cloud: "Na Nuvem",
      initialPlan: "Plano Inicial",
      available: "Disponível",
    },
    features: [
      {
        title: "Super Rápido",
        description:
          "Interface otimizada como supermercado. Venda em segundos com código de barras.",
      },
      {
        title: "100% na Nuvem",
        description:
          "Sem instalações. Acesse de qualquer navegador, em qualquer dispositivo.",
      },
      {
        title: "Controle de Estoque",
        description:
          "Gerencie inventário automaticamente a cada venda. Alertas de baixo estoque.",
      },
      {
        title: "Relatórios ao Vivo",
        description:
          "Vendas, caixa, produtos mais vendidos. Tudo atualizado em tempo real.",
      },
      {
        title: "Multiusuário",
        description:
          "Gerencie caixas e administradores. Controle de permissões e descontos.",
      },
      {
        title: "Seguro e Confiável",
        description:
          "Seus dados protegidos com Supabase. Backup automático na nuvem.",
      },
    ],
    howItWorks: {
      badge: "Como funciona",
      title: "Configure, venda e cresça",
      subtitle: "Tudo pronto em minutos, sem instalações ou hardware extra.",
      steps: [
        {
          title: "Configure seu negócio",
          description:
            "Adicione produtos, preços e usuários em minutos de qualquer dispositivo.",
        },
        {
          title: "Venda mais rápido",
          description:
            "Código de barras, atalhos e recibos prontos para cobrar sem fricção.",
        },
        {
          title: "Controle sua operação",
          description:
            "Relatórios ao vivo, estoque e caixa em um só lugar, sempre atualizado.",
        },
      ],
    },
    cta: {
      title: "Pronto para modernizar seu negócio?",
      subtitle:
        "Junte-se a centenas de negócios que já usam VentaPlus para vender mais rápido",
      startFreeNow: "Começar Gratuitamente Agora →",
      noCard: "Sem cartão de crédito • Configuração em 2 minutos",
    },
  },
  dashboard: {
    welcome: "Bem-vindo",
    currentPlan: "Seu plano atual",
    planBasic: "Plano Básico",
    planProfessional: "Plano Profissional",
    planEnterprise: "Plano Empresarial",
    upgradeToPro: "Atualizar para Pro",
    status: "Status",
    nextRenewal: "Próxima Renovação",
    posSale: "Venda POS",
    cashRegister: "Caixa rápido",
    products: "Produtos",
    inventory: "Gerenciar inventário",
    reports: "Relatórios",
    analytics: "Ver análises",
    admin: "Admin",
    systemSettings: "Configurações do sistema",
    quickStats: "Estatísticas Rápidas",
    salesToday: "Vendas Hoje",
    totalRevenue: "Receita Total",
  },
  errors: {
    generic: "Algo deu errado. Por favor, tente novamente",
    unauthorized: "Não autorizado",
    invalidOrExpiredToken: "Token inválido ou expirado",
    missingAuthHeader: "Cabeçalho de autorização ausente",
    forbidden: "Acesso negado",
    notFound: "Não encontrado",
    serverError: "Erro do servidor",
    networkError: "Erro de conexão",
    validationError: "Erro de validação",
    productCodeRequired: "O código do produto é obrigatório",
    productNameRequired: "O nome do produto é obrigatório",
    productPriceRequired: "O preço do produto é obrigatório",
    invalidPrice: "O preço deve ser um número válido",
    productCreated: "Produto criado com sucesso",
    productUpdated: "Produto atualizado com sucesso",
    productDeleted: "Produto excluído com sucesso",
    errorCreatingProduct: "Erro ao criar o produto",
    errorUpdatingProduct: "Erro ao atualizar o produto",
    errorDeletingProduct: "Erro ao excluir o produto",
    errorFetchingProducts: "Erro ao buscar os produtos",
    invalidEmail: "Endereço de email inválido",
    passwordTooShort: "A senha deve ter pelo menos 6 caracteres",
    passwordsDoNotMatch: "As senhas não correspondem",
    userAlreadyExists: "O usuário já existe",
    invalidCredentials: "Credenciais inválidas",
    sessionExpired: "Sua sessão expirou. Faça login novamente",
    errorSaving: "Erro ao salvar",
    errorLoading: "Erro ao carregar",
    errorDeleting: "Erro ao excluir",
    noOpenCashRegister: "Nenhum caixa aberto",
    invalidAction: "Ação inválida",
    invalidAmount: "Valor inválido",
    internalServerError: "Erro interno do servidor",
    missingRequiredFields: "Campos obrigatórios ausentes",
    errorLoadingConfig: "Erro ao carregar configuração",
    clientNameRequired: "Você deve inserir o nome do cliente",
    cuitRequired: "CUIT é obrigatório para faturas ARCA",
    ivaTypeRequired: "Selecione o tipo de IVA para faturas ARCA",
    companyNameRequired: "Nome da empresa é obrigatório",
    cuitRucDniRequired: "CUIT/RUC/CPF é obrigatório",
    billingEmailRequired: "Email de faturamento é obrigatório",
    errorSavingSupplier: "Erro ao salvar fornecedor",
    supplierDeletedSuccess: "Fornecedor excluído com sucesso",
    errorDeletingSupplier: "Erro ao excluir fornecedor",
    selectValidCSV: "Por favor, selecione um arquivo CSV válido",
    emptyCSVFile: "O arquivo CSV está vazio ou não tem dados",
    csvMustContainName: 'O CSV deve conter pelo menos a coluna "nome"',
    noValidSuppliersFound: "Nenhum fornecedor válido encontrado no arquivo",
    errorProcessingCSV: "Erro ao processar arquivo CSV",
    suppliersImportedSuccess: (count: number) =>
      `${count} fornecedores importados com sucesso`,
    errorLoadingSales: "Erro ao carregar vendas",
    errorRegisteringPurchase: "Erro ao registrar compra",
    purchaseRegisteredSuccess: "Compra registrada com sucesso!",
    paymentError: "Erro no pagamento",
    errorCompletingSale: "Erro ao completar venda",
    errorProcessingSale: "Erro ao processar venda. Tente novamente",
    noDataToExport: "Nenhum dado para exportar",
    confirmDeleteExpense: "Tem certeza de que deseja excluir esta despesa?",
    productCodeExists: "O código do produto já existe",
    emailInUse: "O email já está em uso",
    cannotDeleteSelf: "Você não pode se excluir",
    invalidPlanId: "Plano inválido",
    noFileReceived: "Nenhum arquivo recebido",
    invalidFile: "Arquivo inválido",
    errorImportingProducts: "Erro ao importar produtos",
  },
  messages: {
    welcome: "Bem-vindo",
    goodbye: "Adeus",
    confirmDelete: "Tem certeza de que deseja excluir isso?",
    confirmAction: "Tem certeza?",
    processing: "Processando...",
    loading: "Carregando...",
    noResults: "Sem resultados",
    noData: "Nenhum dado disponível",
  },
  auth: {
    login: {
      title: "Entrar",
      email: "Email",
      password: "Senha",
      submit: "Entrar",
      forgotPassword: "Esqueceu sua senha?",
      noAccount: "Não tem uma conta?",
      registerLink: "Registrar",
    },
    forgotPassword: {
      title: "Recuperar Senha",
      subtitle:
        "Digite seu email e enviaremos um link para redefinir sua senha",
      email: "Email",
      submit: "Enviar Link de Recuperação",
      backToLogin: "Voltar ao login",
      emailSent: "Email enviado",
      emailSentMessage:
        "Se existir uma conta com esse email, você receberá um link de recuperação",
    },
    resetPassword: {
      title: "Redefinir Senha",
      subtitle: "Digite sua nova senha",
      password: "Nova Senha",
      confirmPassword: "Confirmar Nova Senha",
      submit: "Redefinir Senha",
      success: "Senha redefinida com sucesso",
      invalidToken: "O link de recuperação é inválido ou expirou",
    },
    register: {
      title: "Registrar",
      fullName: "Nome Completo",
      email: "Email",
      password: "Senha",
      confirmPassword: "Confirmar Senha",
      submit: "Criar Conta",
      haveAccount: "Já tem uma conta?",
      loginLink: "Entrar",
    },
  },
  pricing: {
    title: "Planos simples e transparentes",
    subtitle: "Comece grátis e cresça quando precisar",
    free: "Plano Gratuito",
    freePrice: "$0",
    freeSubtitle: "para sempre",
    freeDescription: "Ideal para começar",
    pro: "Plano Pro",
    proPrice: "$24.990",
    proSubtitle: "ARS/mês",
    proDescription: "Sem limites para crescer",
    mostPopular: "Mais Popular",
    freeFeatures: [
      "Até 100 produtos",
      "Até 2 usuários",
      "Ponto de venda completo",
      "Controle de caixa",
      "Relatórios básicos",
      "Estoque básico",
    ],
    proFeatures: [
      "Produtos ilimitados",
      "Usuários ilimitados",
      "Tudo do plano gratuito",
      "Gerenciamento de clientes",
      "Vendas a crédito",
      "Gerenciamento de despesas",
      "Relatórios avançados",
      "Suporte prioritário",
    ],
    startFree: "Começar Gratuitamente",
    tryFree: "Tente 14 dias grátis",
  },
  subscriptionProModal: {
    titlePrefix: "Assinatura -",
    billingInfo: "Informações de faturamento",
    fields: {
      businessNameLabel: "Nome da Empresa",
      businessNamePlaceholder: "Nome da sua empresa",
      cuitRucDniLabel: "CUIT/RUC/CPF",
      cuitRucDniPlaceholder: "20-12345678-9",
      billingEmailLabel: "Email de Faturamento",
      billingEmailPlaceholder: "faturamento@suaempresa.com",
      phoneLabel: "Telefone",
      phonePlaceholder: "+55 11 91234-5678",
    },
    buttons: {
      continuePayment: "Continuar para o Pagamento",
      processing: "Processando...",
    },
  },
  navigation: {
    home: "Início",
    dashboard: "Painel de Controle",
    products: "Produtos",
    sales: "Vendas",
    customers: "Clientes",
    reports: "Relatórios",
    settings: "Configurações",
    profile: "Perfil",
  },
  profile: {
    title: "Perfil",
    account: "Conta",
    loading: "Carregando perfil",
    personalInfo: "Informação pessoal",
    userData: "Dados do usuário",
    updateDescription: "Atualize seu nome e email. A senha é opcional.",
    goToDashboard: "Ir ao painel",
    fullName: "Nome completo",
    email: "Email",
    phone: "Telefone",
    phonePlaceholder: "Ex: +55 11 91234 5678",
    role: "Função",
    businessName: "Nome do negócio",
    businessPlaceholder: "Seu comércio",
    password: "Senha (opcional)",
    passwordPlaceholder: "Deixe em branco para manter",
    reset: "Redefinir",
    save: "Salvar alterações",
    updateSuccess: "Perfil atualizado com sucesso",
    updateError: "Não foi possível salvar. Tente novamente.",
    updateErrorGeneric: "Não foi possível atualizar o perfil",
    back: "Voltar",
  },
  pos: {
    nav: {
      posSale: "Ponto de Venda",
      cashRegister: "Caixa",
      products: "Produtos",
      categories: "Categorias",
      stock: "Estoque",
      clients: "Clientes",
      suppliers: "Fornecedores",
      expenses: "Despesas",
      reports: "Relatórios",
      fiscalReports: "Relatórios Fiscais",
      users: "Usuários",
      keyboardConfig: "Configurações de Teclado",
      businessConfig: "Configurações de Negócio",
      planComparison: "Comparação de Planos",
    },
    labels: {
      add: "Adicionar",
      edit: "Editar",
      delete: "Excluir",
      save: "Salvar",
      cancel: "Cancelar",
      search: "Pesquisar",
      filter: "Filtrar",
      sort: "Classificar",
      import: "Importar",
      export: "Exportar",
      print: "Imprimir",
      actions: "Ações",
      name: "Nome",
      description: "Descrição",
      price: "Preço",
      code: "Código",
      quantity: "Quantidade",
      total: "Total",
      subtotal: "Subtotal",
      tax: "Imposto",
      discount: "Desconto",
      payment: "Pagamento",
      customer: "Cliente",
      date: "Data",
      time: "Hora",
      status: "Status",
      active: "Ativo",
      inactive: "Inativo",
      pending: "Pendente",
      completed: "Concluído",
      cancelled: "Cancelado",
    },
    messages: {
      confirmDelete: "Tem certeza de que deseja excluir isso?",
      noData: "Sem dados disponíveis",
      loading: "Carregando...",
      errorLoading: "Erro ao carregar dados",
      clientFetchError: "Erro ao carregar clientes",
      selectClient: "Selecionar cliente...",
      noClients: "Nenhum cliente",
      clientsUpgradeRequired:
        "Pesquisa de clientes disponível apenas no plano Pro",
      errorCreating: "Erro ao criar item",
      errorUpdating: "Erro ao atualizar item",
      errorDeleting: "Erro ao excluir item",
      successCreate: "Item criado com sucesso",
      successUpdate: "Item atualizado com sucesso",
      successDelete: "Item excluído com sucesso",
      required: "Este campo é obrigatório",
      selectOne: "Por favor selecione um item",
    },
    pages: {
      pos: {
        title: "Ponto de Venda",
        noProducts: "Sem produtos para vender",
        selectProduct: "Selecione um produto",
        quantity: "Quantidade",
        addToCart: "Adicionar ao Carrinho",
        cart: "Carrinho",
        total: "Total",
        clearCart: "Limpar Carrinho",
        checkout: "Checkout",
        cash: "Dinheiro",
        card: "Cartão",
        transfer: "Transferência",
      },
      products: {
        title: "Produtos",
        addProduct: "Adicionar Produto",
        editProduct: "Editar Produto",
        deleteProduct: "Excluir Produto",
        productCode: "Código do Produto",
        productName: "Nome do Produto",
        description: "Descrição",
        price: "Preço",
        cost: "Custo",
        quantity: "Quantidade",
        category: "Categoria",
        supplier: "Fornecedor",
        barcode: "Código de Barras",
      },
      categories: {
        title: "Categorias",
        addCategory: "Adicionar Categoria",
        editCategory: "Editar Categoria",
        deleteCategory: "Excluir Categoria",
        categoryName: "Nome da Categoria",
        description: "Descrição",
      },
      stock: {
        title: "Estoque",
        inventory: "Inventário",
        quantity: "Quantidade",
        alertLevel: "Nível de Alerta",
        lastUpdate: "Última Atualização",
        adjustStock: "Ajustar Estoque",
        stockHistory: "Histórico de Estoque",
      },
      clients: {
        title: "Clientes",
        addClient: "Adicionar Cliente",
        editClient: "Editar Cliente",
        deleteClient: "Excluir Cliente",
        name: "Nome",
        email: "Email",
        phone: "Telefone",
        address: "Endereço",
        city: "Cidade",
        state: "Estado",
        zipCode: "CEP",
        creditLimit: "Limite de Crédito",
        creditUsed: "Crédito Usado",
      },
      suppliers: {
        title: "Fornecedores",
        addSupplier: "Adicionar Fornecedor",
        editSupplier: "Editar Fornecedor",
        deleteSupplier: "Excluir Fornecedor",
        name: "Nome",
        email: "Email",
        phone: "Telefone",
        address: "Endereço",
        city: "Cidade",
        state: "Estado",
        contact: "Contato",
      },
      expenses: {
        title: "Despesas",
        addExpense: "Adicionar Despesa",
        editExpense: "Editar Despesa",
        deleteExpense: "Excluir Despesa",
        description: "Descrição",
        amount: "Valor",
        category: "Categoria",
        date: "Data",
        paymentMethod: "Método de Pagamento",
      },
      reports: {
        title: "Relatórios",
        salesReport: "Relatório de Vendas",
        stockReport: "Relatório de Estoque",
        expensesReport: "Relatório de Despesas",
        clientsReport: "Relatório de Clientes",
        profitReport: "Relatório de Lucro",
        dateRange: "Intervalo de Datas",
        exportPDF: "Exportar para PDF",
        exportExcel: "Exportar para Excel",
        totalSales: "Total de Vendas",
        totalExpenses: "Total de Despesas",
        totalProfit: "Total de Lucro",
      },
      cashRegister: {
        title: "Caixa",
        openCash: "Abrir Caixa",
        closeCash: "Fechar Caixa",
        balance: "Saldo",
        initialAmount: "Valor Inicial",
        finalAmount: "Valor Final",
        expected: "Esperado",
        actual: "Real",
        difference: "Diferença",
        cashRegisterId: "ID do Caixa",
        openedBy: "Aberto por",
        closedBy: "Fechado por",
        openTime: "Hora de Abertura",
        closeTime: "Hora de Fechamento",
        status: "Status",
        open: "Aberto",
        closed: "Fechado",
        movements: {
          opening: "Abertura de caixa",
          withdrawal: "Retirada de caixa",
          creditNote: "Nota de crédito",
          noReason: "Sem motivo especificado",
        },
      },
    },
    ui: {
      loading: "Carregando POS...",
      title: "PDV - {role}",
      closedTitle: "Caixa Fechada",
      closedDescription:
        'Você deve abrir uma caixa na seção "Controle de Caixa" para começar a vender',
      scanPlaceholder: "Escanear ou digitar código de barras... (F6)",
      searchPlaceholder: "Buscar produto por nome ou código... (F5)",
      searching: "Pesquisando...",
      tipsTitle: "Dicas rápidas:",
      tipsBodyStart: "Use o leitor de código ou busque pelo nome. Navegue com",
      tipsBodyEnd: "e pressione",
      tipsBodyAdd: "para adicionar.",
      startTyping: "Comece a digitar para buscar",
      noProductsFound: "Nenhum produto encontrado",
      codeLabel: "Código:",
      stockLabel: "Estoque:",
      addButton: "Adicionar",
      cartTitle: "Carrinho",
      clearCart: "Limpar Carrinho",
      cartEmpty: "Carrinho vazio",
      cartEmptySubtitle: "Escaneie ou busque produtos para começar",
      remove: "Remover",
      quantity: "Qtd.",
      discount: "Desconto",
      total: "Total",
      subtotal: "Subtotal",
      totalDiscount: "Desconto",
      tax21: "IVA 21%",
      discountLimitExceeded: "O desconto excede seu limite",
      discountInvalid: "Desconto inválido",
      discountNegative: "O desconto deve ser 0 ou maior",
      discountExceedsSubtotal:
        "O desconto não pode exceder o subtotal da linha",
      discountExceedsUserLimit: "O desconto excede seu limite",
      weightQuantityHint:
        "Use ponto para decimais e vírgula para milhares (ex.: 1.560 ou 1,560)",
      paymentMethod: "Forma de Pagamento",
      paymentOptions: {
        cash: "Dinheiro",
        card: "Cartão",
        check: "Cheque",
        online: "Online",
        bankTransfer: "Transferência Bancária",
        qr: "Código QR",
        account: "Conta corrente",
      },
      accountLabel: "Conta",
      balanceLabel: "Saldo",
      balanceDueLabel: "Saldo em aberto",
      balanceCreditLabel: "Saldo a favor",
      viewAccount: "Ver conta",
      accountTitle: "Conta do cliente",
      registerPayment: "Registrar pagamento",
      paymentAmount: "Valor",
      paymentNote: "Detalhe",
      savePayment: "Salvar pagamento",
      accountMovements: "Movimentos",
      noAccountMovements: "Sem movimentos",
      accountCharge: "Cobrança",
      accountPayment: "Pagamento",
      accountAdjustment: "Ajuste",
      accountLoadError: "Erro ao carregar conta",
      accountPaymentSaved: "Pagamento registrado",
      accountPaymentError: "Erro ao registrar pagamento",
      accountRequiresClient: "Selecione um cliente para cobrar na conta",
      accountInvalidAmount: "Valor inválido",
      accountOverpayError: "O pagamento excede o saldo em aberto",
      processing: "Processando...",
      checkout: "Finalizar Venda",
      checkoutSuccess: "Venda concluída com sucesso!",
      checkoutError: "Erro ao finalizar a venda",
      checkoutProcessError: "Erro ao processar a venda. Tente novamente.",
      insufficientStock:
        "Estoque insuficiente para {name}. Disponível: {available}, solicitado: {requested}",
      roles: {
        admin: "Administrador",
        supervisor: "Supervisor",
        cashier: "Caixa",
        user: "Usuário",
      },
      // Keyboard POS translations
      keyboardPOS: "PDV por Teclado",
      quantityFirst: "Digite a quantidade primeiro, depois o código do produto",
      productCodeBarcode: "Código do Produto / Código de Barras",
      scanOrEnterCode: "Escaneie ou digite o código...",
      pressEnterToAdd: "Pressione Enter para adicionar • Esc para cancelar",
      keyboardShortcuts: "Atalhos de Teclado",
      confirmAdd: "Confirmar / Adicionar",
      cancel: "Cancelar / Limpar",
      multiplier: "Multiplicador (50*código)",
      changeCustomer: "Mudar cliente",
      findCustomer: "Buscar cliente",
      newCustomer: "Novo cliente",
      removeCustomer: "Remover cliente",
      examples: "Exemplos",
      example1:
        "Digite '5' → Enter → Escaneie/Digite código → Enter = 5 unidades",
      example2: "Digite '0.325' → Enter → Escaneie = 0.325 kg",
      example3:
        "Digite '50*697202601252361' → Enter = 50 unidades instantaneamente",
      quantityHint: "Digite a quantidade ou use multiplicador: 50*código",
      enterProductCode: "Por favor, digite um código de produto",
      invalidQuantity: "Quantidade inválida",
      productNotFound: "Produto não encontrado",
      outOfStock: "Produto sem estoque",
      addedToCart: "adicionado ao carrinho",
      errorAddingProduct: "Erro ao adicionar produto",
      changeCustomerType: "Mudar tipo de cliente",
      searchCustomer: "Buscar cliente",
      advancedSearch: "Busca Avançada",
      clickToExpand: "Clique para expandir",
    },
  },
};

const translations: Record<Language, Record<string, any>> = {
  es: translationsEs,
  en: translationsEn,
  pt: translationsPt,
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language") as Language;
      if (saved && ["es", "en", "pt"].includes(saved)) return saved;
    }
    return "en";
  });
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    const savedLanguage =
      (localStorage.getItem("language") as Language) || "en";
    const initialLanguage: Language = ["es", "en", "pt"].includes(savedLanguage)
      ? savedLanguage
      : "en";

    setCurrentLanguage(initialLanguage);
    localStorage.setItem("language", initialLanguage);
    document.documentElement.lang = initialLanguage;
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem("language", lang);
    document.documentElement.lang = lang;
    // Notify all subscribers about language change
    notifyLanguageChange(lang);
  };

  const t = (key: string, namespace: string = "common"): any => {
    const keys = key.split(".");
    let value = translations[currentLanguage][namespace];

    for (const k of keys) {
      value = value?.[k];
    }

    return value ?? key;
  };

  return (
    <LanguageContext.Provider
      value={{ currentLanguage, setLanguage: handleSetLanguage, t }}
    >
      {isClient && children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
